### ISSUE TITLE
Playground uses old version of compiler

### ISSUE THREAD

**Issue by robpalme** [bloomberg/ts-blank-space#23]
[`play.js`](https://github.com/bloomberg/ts-blank-space/blob/gh-pages/play/play.js) has not be regenerated in two months so the playground website is out of date.

It would also be nice for the playground to say which version it using.

**Comment by acutmore** [comment]
Agreed. Now that it's published to npm the site can pull the latest dynamically using a cdn like https://esm.sh/.

A follow would be to even allow the version to be selected, which can be useful for bisecting.

**Comment by acutmore** [comment]
Opened https://github.com/bloomberg/ts-blank-space/issues/24
